# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import weather_bot_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_token', models.CharField(blank=True, max_length=255, null=True)),
                ('order_email', models.EmailField(help_text='\u0421\u044e\u0434\u0430 \u0431\u0443\u0434\u0435\u0442 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c\u0441\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0437\u0430\u043a\u0430\u0437\u0435', max_length=254, null=True)),
                ('hello_description', models.CharField(default='', help_text='\u041d\u0430\u0447\u0430\u043b\u044c\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u043b\u0435 /start', max_length=1000)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotAdministratorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotBuyerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_blocked_by_user', models.BooleanField(default=False)),
                ('dialog_with_support', models.TextField(null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_buyer_map_rel', to='weather_bot_app.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('telegram_user_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Bot')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='PostponedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u043b\u043e\u0436\u0435\u043d\u0438\u044f/\u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=weather_bot_app.models.postponed_post_path, verbose_name='\u0424\u043e\u0442\u043e \u0434\u043b\u044f \u043d\u043e\u0432\u043e\u0441\u0442\u0438')),
                ('send_at', models.DateTimeField(verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0432')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='PostponedPostResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Buyer')),
                ('postponed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.PostponedPost')),
            ],
        ),
        migrations.AddField(
            model_name='botbuyermap',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_buyer_map_rel', to='weather_bot_app.Buyer'),
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_support',
            field=models.ForeignKey(blank=True, help_text='\u0427\u0435\u043b\u043e\u0432\u0435\u043a, \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u0431\u0443\u0434\u0443\u0442 \u043f\u0435\u0440\u0435\u043d\u0430\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c\u0441\u044f \u0432\u0441\u0435 \u0432\u043e\u043f\u0440\u043e\u0441\u044b \u0438\u0437 \u0431\u043e\u0442\u0430', null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Buyer'),
        ),
    ]
