# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(choices=[(b'minsk', b'MINSK'), (b'kiev', b'KIEV'), (b'moscow', b'MOSCOW'), (b'piter', b'PITER')], default=b'minsk', max_length=255),
        ),
    ]
