# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot_app', '0002_buyer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.CharField(choices=[(b'kiev', b'KIEV'), (b'moscow', b'MOSCOW'), (b'minsk', b'MINSK'), (b'piter', b'PITER')], default=b'moscow', max_length=255),
        ),
    ]
