# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot_app', '0003_auto_20170826_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_notification_at', models.DateTimeField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Buyer')),
            ],
        ),
    ]
