# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot_app', '0004_weatherscheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSchedulerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_at', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='is_schedule_enabled',
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_bot_blocked',
            field=models.BooleanField(default=False, help_text='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u0437\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u043b \u0431\u043e\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='weatherscheduler',
            name='is_schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weatherscheduler',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_scheduler_rel', to='weather_bot_app.Buyer'),
        ),
        migrations.AddField(
            model_name='weatherschedulerresult',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_bot_app.Buyer'),
        ),
    ]
