# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot_app', '0006_remove_buyer_is_bot_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[(b'kiev', b'KIEV'), (b'moscow', b'MOSCOW'), (b'minsk', b'MINSK'), (b'piter', b'PITER')], default=b'moscow', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postponedpost',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='postponedpostresult',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='postponedpostresult',
            name='postponed_post',
        ),
        migrations.DeleteModel(
            name='PostponedPost',
        ),
        migrations.DeleteModel(
            name='PostponedPostResult',
        ),
    ]
